name = "ReviseTests"
uuid = "a8315d63-8160-44e4-a573-aa779bc83c34"
authors = ["Bagaev Dmitry <bvdmitri@gmail.com> and contributors"]
version = "1.0.0"

[deps]
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
